version: '3.4'

services:
  contactbookdb:
    container_name: contactbookdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  contactbook.api:
    container_name: contactbook.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString:=mongodb://contactbookdb:27017"
    depends_on:
      - contactbookdb
    ports:
      - "8000:80"
